### ISSUE TITLE
Forces in local coordinates

### ISSUE THREAD

**Issue by albertoferna** [RubendeBruin/DAVE#116]
Hello,
The only way to define forces seems to be in global coordinates. There are use cases where having them in defined in local coordinates is usefull.
Hand in hand with this, those forces could be made followers (in FEA parlance) so they actually move with the assigned point.
This is a whish more than an issue, Just writing it here in case it becomes interesting

**Comment by RubendeBruin** [comment]
Hi albertoferna, I think in general it is fine to use "issues" for anything from bug to showing off you work :-) 
I did not include local forces initially because they were troublesome with the solver. But at the moment I'm upgrading the solver and I think local forces would be easy to add. So it is on the list.

**Comment by RubendeBruin** [comment]
Hi @albertoferna , followers will be included in version 2.1 (to be realsed today)

<img width="661" alt="image" src="https://github.com/RubendeBruin/DAVE/assets/34062862/a1638c2e-3a31-4cc2-b824-3fde515166ba">

**Comment by RubendeBruin** [comment]
closed because implemented in 2.1
