### ISSUE TITLE
Error with reporting in Jupyter lab

### ISSUE THREAD

**Issue by michielbicker** [RubendeBruin/DAVE#60]
Since now I get an error when I try to report basic information in Jupyter lab, see figure below. Are you familiar with this one?

![image](https://user-images.githubusercontent.com/89965911/131798622-cef07d73-1358-4d6a-91b8-4f1ceff13f8c.png)

**Comment by RubendeBruin** [comment]
Hi @michielbicker, this is a bug resulting from the recent rename of Axis to Frame. It seems that you have an outdated version of proplist.csv.
This has been solved in the "master" branch but may still be an issue in the most recent release.

A quick solve of this issue is to do a local search of `Axis` and replace with `Frame` in the file DAVE/resources/proplist.csv

**Comment by michielbicker** [comment]
Ha @RubendeBruin, thanks! It seems to solve some of the issue, now I get the following:
![image](https://user-images.githubusercontent.com/89965911/131980017-69ce0f42-6044-4987-b37f-95f89cd64270.png)
Is that related?

**Comment by RubendeBruin** [comment]
Yes it is, sorry. Axis to Frame apparently was not the only change I made.

The correct proplist.csv is here:

https://raw.githubusercontent.com/RubendeBruin/DAVE/master/src/DAVE/resources/proplist.csv

if you use that then reporting should work again.

**Comment by RubendeBruin** [comment]
Should be solved in release 1.7.0.
